//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMB.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequimentExport
    {
        public int OrderID { get; set; }
        public System.DateTime CreateDay { get; set; }
        public int StatusRequiment { get; set; }
        public int IdRequiment { get; set; }
    }
}
